# -*- coding: utf-8 -*-
"""Modele_temp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HXCREqi-V9Ay0oPJUqFcHjcQ47Df9xr0
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/seattle-weather.csv")

df.head()

df.info()

df.isna().sum()

df['date'] = pd.to_datetime(df['date'])
df.head()

df.nunique()

plt.figure(figsize=(18,6))
sns.pairplot(df.drop('date',axis=1),hue='Precipitation')
plt.show()

sns.lmplot(x='Himidity',y='Precipitation', data=df, ci=None)

sns.lmplot(x='Themperature',y='Precipitation', data=df, ci=None)

df.columns

df=df.drop(columns=['date'])

X=df.drop(columns=['Themperature'])

y=df.drop(columns=['Precipitation', 'Himidity'])

X.columns

y.columns

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

X_train=X_train.astype('float')
y_train=y_train.astype('float')

"""Regression

---


"""

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

model.predict([[73.5,0.2]])

from sklearn.metrics import r2_score

r2_a_score = model.score(X_test,y_test)
print(r2_a_score*100,'%')

"""*SGDClassifier*



---


"""

import numpy as np
y1 = y_train.values.ravel()
train_y1 = np.array(y1).astype(int)
from sklearn.linear_model import SGDClassifier
classifier_sgdc=SGDClassifier()
classifier_sgdc.fit(X_train,train_y1)

y1 = y_test.values.ravel()
test_y1 = np.array(y1).astype(int)
r2_a_score = classifier_sgdc.score(X_test,test_y1)
print(r2_a_score*100,'%')

"""GaussianNB



---


"""

from sklearn.naive_bayes import GaussianNB

gas = GaussianNB()
gas.fit(X_train,train_y1)

r2_a_score = gas.score(X_test,test_y1)
print(r2_a_score*100,'%')

#import joblib

#joblib.dump(model,'model_temperature.pkl')

import pickle
pickle.dump(gas, open("model_temperature.pkl", "wb"))